server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-cla ss-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/begroom?rewriteBatchedStatements=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 50
      minimum-idle: 50

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_updates: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  Prometheus:
    metrics:
      export:
        enabled: true
  influx:
    metrics:
      export:
        enabled: true
        uri: http://localhost:8086
        bucket: k6
        db: k6
        step: 10s
        auto-create-db: true