server:
  port: 8080
  tomcat:
    threads:
      max: 200        # default: 200
      min-spare: 10   # default: 10
    accept-count: 100

logging:
  level:
    root: WARN
    org.springframework.transaction: WARN #spring 트랜잭션 매니저 로그
    org.springframework.orm.jpa.JpaTransactionManager: WARN #JPA 연동 트랜잭션 매니저 클래스의 로그
    com.example.BeGroom.settlement: INFO
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE # 파라미터 바인딩까지 보고 싶을 때

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/begroom?rewriteBatchedStatements=true
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
#          batch_size: 200        # allocationSize와 동일
          order_inserts: true   # insert 쿼리끼리 정렬
          order_updates: true   # update 쿼리끼리 정렬
          batch_versioned_data: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  Prometheus:
    metrics:
      export:
        enabled: true
  influx:
    metrics:
      export:
        enabled: true
        uri: http://localhost:8086
        bucket: k6
        db: k6
        step: 10s
        auto-create-db: true