#apiVersion: 1
#
#datasources:
#  - name: k6
#    type: influxdb
#    access: proxy
#    url: http://influxdb:8086
#    database: k6
#    isDefault: true

apiVersion: 1

datasources:
  # Prometheus 설정
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090  # 컴포즈 서비스 이름 사용
    access: proxy
    isDefault: true

  # InfluxDB (k6 결과 저장용) 설정
  - name: influxdb
    type: influxdb
    url: http://influxdb:8086
    database: k6
    access: proxy