global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['15.165.234.125:8080', '54.180.130.39:8080'] # 관측할 PC